series: Intermediate C++
title: Smart Pointers
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Use templates to define generic classes.
language: C++
tags:
  - Core
extra_resources:
  - link: http://stackoverflow.com/questions/106508/what-is-a-smart-pointer-and-when-should-i-use-one
    title: Stack Overflow: What is a smart pointer and when should I use one?
  - link: http://gamedev.stackexchange.com/questions/2578/c-smart-pointers-raw-pointers-no-pointers
    title: C++: Smart pointers, Raw pointers, No Pointers?
  - link: http://en.cppreference.com/w/cpp/memory
    title: Documentation on smart pointers in the C++ standard.
connections:
  - series: Intermediate C++
    title: Class Templates